#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor VGA-0   -d 5 6 7
bspc monitor DVI-D-0   -d 8 9 10
bspc monitor HDMI-0   -d 1 2 3 4 "VB/BT/Volume"
# bspc monitor HDMI-0  -d 1 2 3 4 "VB/BT/Volume" "Social" 11 12

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a "VirtualBox Manager" desktop="VB/BT/Volume" follow=on
bspc rule -a "Blueman-manager" desktop="VB/BT/Volume" follow=on
bspc rule -a "Pavucontrol" desktop="VB/BT/Volume" follow=on

bspc config focus_follows_pointer true;
# bspc node -f "$direction"; \
bspc config pointer_follows_focus true;
